### ISSUE TITLE
Should run with Java 7

### ISSUE THREAD

**Issue by kicktipp** [carlosCharz/fcmxmppserverv2#1]
- pom.xml is missing compiler.target 1.7 therefore Eclipse is annoyed about @Override annotations for implemented methods (allowed since 1.6)
- In CssClient Java8 lambdas are used. This project can easily run with 1.7 so it should in my opinion. 

I will send you a PR

**Comment by carlosCharz** [comment]
Thanks man. I am gonna improve the pom with your pom changes.
