### ISSUE TITLE
how to run the server in debug mode with jar

### ISSUE THREAD

**Issue by guid1984** [carlosCharz/fcmxmppserverv2#16]
Hi Carlos,

The xmpp server project only produces jar file. Shall I specify EntryPoint.java as main class in my pom.xml to launch the xmpp server for my development? Thanks

-Himanshu

**Comment by carlosCharz** [comment]
Hi @guid1984 
1. You can customize to use it as a jar. To be honest I do not know how it works specifically. I remember that there is a way to do so. I was running it: java -jar /home/ec2-user/fcm/xmpp-server.jar
2. You can run it as a command line providing the main entry point class. 
3. You can can deploy it in a container. The app should be a war in this case.
4. You can use spring boot so you can run it from command line as a war or jar providing the app properties.
5. For debugging purposes I would suggest to run/debug it in eclipse using run/debug configurations. Just put the console parameters in the variables tab . 

Greetings!
