### ISSUE TITLE
Spring Deployment

### ISSUE THREAD

**Issue by famagusta** [carlosCharz/fcmxmppserverv2#20]
Hi,

I am trying to set up this project in spring boot. Have you figured out how to do this?
I am completely new to Spring and XMPP.

Great repo by the way. Thanks for it.

Regards
Robin

**Comment by carlosCharz** [comment]
Hi @famagusta yes I did with spring boot but the core is the same. I am still working with a better solution for the FCM connection draining. The project was migrated to that but it is the same. I just use conf properties. Created some beans. Use the predestroy method, the post construct, etc.
