### ISSUE TITLE
Keep the main thread alive

### ISSUE THREAD

**Issue by thelong1EU** [carlosCharz/fcmxmppserverv2#7]
You can you this to keep the main thread alive:

```
        try {
            CountDownLatch latch = new CountDownLatch(1);
            latch.await();
        } catch (InterruptedException e) {
            logger.log(Level.SEVERE, "An error occurred while latch was waiting.", e);
        }
```

**Comment by carlosCharz** [comment]
Thanks. It worked well!

**Comment by thelong1EU** [comment]
You welcome. I have a strange problem now. It seems like the FCM is sending the same massage multiple times. So you know something about this?

**Comment by carlosCharz** [comment]
I know from the documentation that FCM will try to resend to your server several times until you confirm with an ACK. Check if this is your issue? Check the documentation about the acks you should send. I was doing that in the code. I had no problems now but check it out just in case.

**Comment by thelong1EU** [comment]
You were right! Thanks so much!
