### ISSUE TITLE
CONNECTION_DRAINING handling 

### ISSUE THREAD

**Issue by thelong1EU** [carlosCharz/fcmxmppserverv2#8]
How do you handle CONNECTION_DRAINING message?

I'm doing this:

```
private void handleConnectionDrainingFailure() {
        logger.log(Level.INFO, "FCM Connection is draining! Initiating reconnection ...");

        XMPPTCPConnection oldConnection = connection;
        oldConnection.disconnect();

        try {
            connect();
        } catch (XMPPException | SmackException | IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }
```

**Comment by carlosCharz** [comment]
I have modified a little bit the ccsConnection class but it is almost the same because in connection draining I am calling the reconnect method:

public void reconnection() {
		BackOffStrategy backoff = new BackOffStrategy();
		while (backoff.shouldRetry()) {
			try {
				initialize();
				backoff.doNotRetry();
			} catch (XMPPException | SmackException | IOException e) {
				logger.info("The notifier server could not reconnect after the connection draining message");
				backoff.errorOccured();
			}
		}
	}

@PostConstruct
	public void initialize() throws XMPPException, SmackException, IOException {
		// Create the connection
		connection = new XMPPTCPConnection(connConfiguration);

		// Connect
		connection.connect();

...

// Login to FCM

}

Hope it helps

**Comment by carlosCharz** [comment]
Hi @long1eu 

I just pushed the connection draining logic to the main branch if you want to check it out. Links:

- Github: https://github.com/carlosCharz/fcmxmppserverv2
- Youtube: https://youtu.be/KVKEj6PeLTc

Hope you can find it useful. Greetings!

**Comment by long1eu** [comment]
Thank you so much! Hope you're well!
